--github copilot
--friendly snippets fix
--dubugger nvim-dap plugin
--language autoformatiing
--install plugins to make neovim more fun and easier to use
--oil nvim, mark nvim, conform nvim, surround nvim, leap nvim, gitsigns.nvim, tpope/vim-fugitive, nvim-autopairs, hop or easymotion, mrjones2014/smart-splits.nvim, nvim-focus/focus.nvim, rmagatti/auto-session, gelguy/wilder.nvim, trouble,petertriho/nvim-scrollbar,karb94/neoscroll.nvim, folke/neodev.nvim, kevinhwang91/nvim-bqf, mfussenegger/nvim-dap, dressing, guess indent, trouble, multicursor, tagbar, coc.nvim, nvim-ts-autotag, ThePrimeagen/refactoring.nvim, noice
--find a project management plugin
--awesome neovim github plugins
--Cheatsheet/help menu(add hidden keymaps like gc from comments and also all the default keymaps :h index :h keycodes)
--separate and better file structure than just one having 1 file and not looking cool
--fix E, R change to icons
--add terminal intergration
--add more awesome plugins
--reconfigure lualine
--gitsigns
--DAP, Linter, Formmatter, snip
--better conifuration for auto complete and also when showing list of objects in auto complete show icons
--add quit option to dashboard
--Set up properly toggleterm
--"create new file" shortcut
--automatic lsp install
--LSP, LSP functions/Keybinds
--configure treesitter
--change away from IDE style to a more local VIM style
--reconfigure keybinds
--search and replace
--set up whichkey for keybinds
--Project Managemant
--nvim tree automatic change directory
--nvim notify
--set up git(plugins and config and keymaps and other stuff)
--Set up lsp
--Set up autocompletion
--Set up telescope, lsp, treesitter, lists, git
--Automatic install lsp server, automatic setup configuration
--automatic require config directory
--exit all and save all keybinds
--how does dashboard-nvim project work?
--FIX LSP!! and CMP! noice

-- Neovim setup
require("core")
require("plugins")
